source 'https://rubygems.org'

gem 'bosh_common', '1.3262.24.0'
gem 'bosh_cpi', '2.5.0'
gem "yajl-ruby", ">=1.3"
gem "builder","~>3.1.4"
gem "rest-client", "~>1.6.7"
gem "nokogiri", "~>1.10.7"
gem "membrane"

group :test, :development do
  gem 'ci_reporter_rspec', '~> 1.0'
  gem 'method_profiler'
  gem 'rake', '~> 10.0'
  gem 'rspec', '~> 3.3.0'
  gem 'rubocop', '>= 0.24.1'
  gem 'simplecov'
  gem 'simplecov-rcov'
end
